from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.database.connection import SessionLocal
from app.models.interview_question import InterviewQuestion
from app.services.question_generator import generate_questions


router = APIRouter(
    prefix="/ai",
    tags=["AI Interview"]
)


class QuestionRequest(BaseModel):
    session_id: int
    job_role: str
    difficulty: str = "Medium"
    count: int = 5


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.post("/generate-questions")
def generate_interview_questions(
    request: QuestionRequest,
    db: Session = Depends(get_db)
):
    # Generate questions using Gemini
    questions_text = generate_questions(
        job_role=request.job_role,
        difficulty=request.difficulty,
        count=request.count
    )

    # Split the numbered AI response into individual questions
    questions = []

    for line in questions_text.splitlines():
        line = line.strip()

        if line:
            # Remove numbering such as "1.", "2.", "3." etc.
            cleaned = line.lstrip("0123456789").lstrip(".").strip()

            if cleaned:
                questions.append(cleaned)

    if not questions:
        raise HTTPException(
            status_code=500,
            detail="No questions were generated by AI."
        )

    # Save questions into database
    saved_questions = []

    for question in questions:
        new_question = InterviewQuestion(
            session_id=request.session_id,
            question=question,
            question_type="AI Generated",
            difficulty=request.difficulty
        )

        db.add(new_question)
        saved_questions.append(new_question)

    db.commit()

    # Refresh IDs generated by PostgreSQL
    for question in saved_questions:
        db.refresh(question)

    return {
        "message": "Questions generated and saved successfully",
        "session_id": request.session_id,
        "job_role": request.job_role,
        "difficulty": request.difficulty,
        "questions": [
            {
                "id": question.id,
                "question": question.question,
                "question_type": question.question_type,
                "difficulty": question.difficulty
            }
            for question in saved_questions
        ]
    }